apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dynamic-dns-ingress
  namespace: dynamic-dns-{{ git_branch }}
spec:
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - backend:
              serviceName: dynamic-dns-service
              servicePort: http4s-port