apiVersion: v1
kind: Secret
metadata:
  name: dynamic-dns-secrets
  namespace: dynamic-dns-{{ git_branch }}
type: Opaque
stringData:
{% for key, value in secrets.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}