apiVersion: v1
kind: Secret
metadata:
  name: dynamic-dns-sync-job-secrets
  namespace: dynamic-dns-{{ git_branch }}
type: Opaque
stringData:
{% for key, value in sync_job.secrets.items() %}
  {{ key }}: "{{ value }}"
{% endfor %}