version: "3"

services:

  dynamic-dns:
    build: .
    # image: dynamic-dns:latest
    ports:
      - 5005:5005
      - 8000:8000
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/Library/Caches/Coursier:/root/.cache/coursier" # MacOS Coursier cache
      #      - "~/.cache/coursier:/root/.cache/coursier" # Linux Coursier cache
      #      - "~/AppData/Local/Coursier/Cache:/root/.cache/coursier" # Windows Coursier cache
      - ".:/opt/dynamic-dns"
      - "/opt/dynamic-dns/target"
      - "/opt/dynamic-dns/project/target"
      - "/root/.sbt/1.0/plugins"
