- set_fact:
    sync_job:
      config_values:
        API_URL: https://ip.ruchij.com
        AWS_REGION: ap-southeast-2
      secrets:
        AWS_ACCESS_KEY_ID: "{{ lookup('aws_ssm', '/dynamic-dns/sync-job/aws-access-key-id', region='ap-southeast-2') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('aws_ssm', '/dynamic-dns/sync-job/aws-secret-access-key', region='ap-southeast-2') }}"
        ALERT_SMS_PHONE_NUMBER: "{{ lookup('aws_ssm', '/dynamic-dns/sync-job/alert-sms-phone-number', region='ap-southeast-2') }}"
