- name: Gather git information
  import_tasks: tasks/git-info.yml

- name: Set config values and secrets
  import_tasks: tasks/configs-and-secrets.yml

- name: Render K8s resource files
  template:
    src: "{{ item }}"
    dest: k8s-output/{{ app_name }}/{{ item | basename }}
  with_fileglob:
    - k8s/{{ app_name }}/*.yaml