- name: Publish Docker image
  shell: |
    docker tag dynamic-dns:{{ git_commit }} {{ docker_registry }}/dynamic-dns:{{ git_commit }} && \
    docker push {{ docker_registry }}/dynamic-dns:{{ git_commit }}