version = 0.1

[default.global.parameters]
stack_name = "dynamic-dns-serverless-api"
region = "ap-southeast-2"

[default.build.parameters]
use_container = true

[default.package.parameters]
resolve_s3 = true

[default.deploy.parameters]
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
