FROM openjdk:17-slim

ENV GIT_BRANCH {{ git_branch }}
ENV GIT_COMMIT {{ git_commit }}
ENV BUILD_TIMESTAMP {{ build_timestamp }}

WORKDIR /opt/dynamic-dns-api

ADD dynamic-dns-api-*.tgz .

EXPOSE 8000

CMD [ "/opt/dynamic-dns-api/bin/dynamic-dns-api" ]
