apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: dynamic-dns-api-certificate
  namespace: dynamic-dns-{{ git_branch }}
spec:
  secretName: dynamic-dns-api-tls
  issuerRef:
    kind: ClusterIssuer
    name: lets-encrypt
  dnsNames:
    - {{ hostname }}