apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: dynamic-dns-api-ingress
  namespace: {{ namespace }}
spec:
  tls:
    - secretName: dynamic-dns-api-tls
      hosts:
        - {{ hostname }}
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - backend:
              serviceName: dynamic-dns-api-service
              servicePort: http4s-port