apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dynamic-dns-api-ingress
  namespace: {{ namespace }}
  annotations:
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  tls:
    - secretName: dynamic-dns-api-tls
      hosts:
        - {{ hostname }}
  rules:
    - host: {{ hostname }}
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: dynamic-dns-api-service
                port:
                  name: http4s-port