---
- hosts: localhost
  connection: local

  tasks:
    - name: Install dependencies
      import_tasks: tasks/install-dependencies.yml

    - name: Build Dynamic DNS API
      import_tasks: tasks/build-docker-prod.yml
      vars:
        app_name: api
        sbt_project: api
        publish: true

    - name: Build Dynamic DNS sync job
      import_tasks: tasks/build-docker-prod.yml
      vars:
        app_name: sync-job
        sbt_project: syncJob
        publish: true
