---
- name: Build Docker images
  import_playbook: build-docker-images.yml

- hosts: localhost
  connection: local

  tasks:
    - name: Dynamic DNS API
      import_tasks: tasks/publish-docker-image.yml
      vars:
        app_name: api

    - name: Dynamic DNS sync job
      import_tasks: tasks/publish-docker-image.yml
      vars:
        app_name: sync-job
