---
- hosts: localhost
  connection: local

  tasks:
    - name: Install dependencies
      import_tasks: tasks/install-dependencies.yml

    - name: Build and publish Dynamic DNS API Docker image
      import_tasks: tasks/build-and-publish-docker-image.yml
      vars:
        app_name: api
        sbt_project: api
        publish: true

    - name: Build and publish Dynamic DNS sync job Docker image
      import_tasks: tasks/build-and-publish-docker-image.yml
      vars:
        app_name: sync-job
        sbt_project: syncJob
        publish: true
