---
- hosts: localhost
  connection: local

  tasks:
    - name: Build Dynamic DNS API Docker image
      import_tasks: tasks/build-and-publish-docker-image.yml
      vars:
        app_name: api
        sbt_project: api
        publish: false

    - name: Build Dynamic DNS sync job Docker image
      import_tasks: tasks/build-and-publish-docker-image.yml
      vars:
        app_name: sync-job
        sbt_project: syncJob
        publish: false