---
- hosts: localhost
  connection: local

  tasks:
    - name: Build Dynamic DNS API
      import_tasks: tasks/build-docker-prod.yml
      vars:
        app_name: api
        sbt_project: api

    - name: Build Dynamic DNS sync job
      import_tasks: tasks/build-docker-prod.yml
      vars:
        app_name: sync-job
        sbt_project: syncJob