---
- hosts: localhost
  connection: local
  vars:
    docker_env_file: ../docker.env

  tasks:
    - name: Set config values and secrets
      import_tasks: tasks/configs-and-secrets.yml

    - name: Delete existing Docker env file
      file:
        path: "{{ docker_env_file }}"
        state: absent

    - name: Write
      copy:
        dest: "{{ docker_env_file }}"
        content: |
          {% for key, value in sync_job.config_values.items() %}
          {{ key }}={{ value }}
          {% endfor %}
          {% for key, value in sync_job.secrets.items() %}
          {{ key }}={{ value }}
          {% endfor %}
