---
- hosts: localhost
  connection: local

  tasks:
    - block:
      - name: Delete existing output directory
        file:
          path: k8s-output
          state: absent

      - name: Create output directory
        file:
          path: k8s-output
          state: directory

      - name: Create API output directory
        file:
          path: k8s-output/api
          state: directory

      - name: Create sync job output directory
        file:
          path: k8s-output/sync-job
          state: directory

    - name: Gather git information
      import_tasks: tasks/git-info.yml

    - name: Render K8s resource files
      block:
        - name: Render K8s Namespace
          template:
            src: k8s/Namespace.yaml
            dest: k8s-output/Namespace.yaml

        - name: Render API K8s resource files
          import_tasks: tasks/k8s-resource-files.yml
          vars:
            docker_registry: localhost:32000
            app_name: api
            hostname: ip.home.ruchij.com

        - name: Render API K8s resource files
          import_tasks: tasks/k8s-resource-files.yml
          vars:
            docker_registry: localhost:32000
            app_name: sync-job

    - name: Set kube_config
      import_tasks: tasks/k8s-config.yml
      vars:
        aws_ssm_k8s_config_path: /k8s/config/home

    - name: Deploy K8s resources
      block:
        - name: Create Namespace
          command: kubectl apply -f k8s-output/Namespace.yaml --kubeconfig k8s-output/kubeconfig

        - name: Deploy API
          block:
            - name: Deploy application
              command: kubectl apply -f k8s-output/api --kubeconfig k8s-output/kubeconfig

            - name: Wait for successful deployment
              command: kubectl rollout status deployment dynamic-dns-api-deployment --kubeconfig k8s-output/kubeconfig -n dynamic-dns-{{ git_branch }}

#        - name: Deploy sync job
#          block:
#            - name: Create ConfigMap
#              command: kubectl apply -f k8s-output/sync-job/ConfigMap.yaml --kubeconfig k8s-output/kubeconfig
#
#            - name: Deploy CronJob
#              command: kubectl apply -f k8s-output/sync-job --kubeconfig k8s-output/kubeconfig

    - name: Clean up output directory
      file:
        path: k8s-output
        state: absent
