---
- hosts: localhost
  connection: local

  tasks:
    - name: Install dependencies
      import_tasks: tasks/install-dependencies.yml

    - block:
      - name: Delete existing output directory
        file:
          path: k8s-output
          state: absent

      - name: Create output directory
        file:
          path: k8s-output
          state: directory

      - name: Create API output directory
        file:
          path: k8s-output/api
          state: directory

      - name: Create sync job output directory
        file:
          path: k8s-output/sync-job
          state: directory

    - name: Gather git information
      import_tasks: tasks/git-info.yml

    - set_fact:
        namespace: "{{ 'dynamic-dns' if git_branch == 'master' else 'dynamic-dns-' + git_branch }}"

    - name: Render K8s resource files
      block:
        - name: Render K8s Namespace
          template:
            src: k8s/Namespace.yaml
            dest: k8s-output/Namespace.yaml

        - name: Render Docker registry credentials
          template:
            src: k8s/DockerRegistryCredentials.yaml
            dest: k8s-output/DockerRegistryCredentials.yaml
          vars:
            ghcr_credentials: "{{ lookup('aws_ssm', '/github/ghcr/docker-config', region='ap-southeast-2') }}"

        - name: Render API K8s resource files
          import_tasks: tasks/k8s-resource-files.yml
          vars:
            app_name: api
            domain: ip.dev.ruchij.com
            hostname: "{{ domain if git_branch == 'master' else git_branch + '.' + domain }}"

        - name: Render sync job K8s resource files
          import_tasks: tasks/k8s-resource-files.yml
          vars:
            app_name: sync-job

    - name: Set kube_config
      import_tasks: tasks/k8s-config.yml

    - name: Deploy K8s resources
      block:
        - name: Create Namespaces
          block:
#            - name: Create Namespace in API server
#              command: kubectl apply -f k8s-output/Namespace.yaml --kubeconfig k8s-output/api-server-kubeconfig

            - name: Create Namespace in Sync job
              command: kubectl apply -f k8s-output/Namespace.yaml --kubeconfig k8s-output/sync-job-kubeconfig

        - name: Create Docker registry credentials
          block:
#            - name: Create Docker registry credentials in API server
#              command: kubectl apply -f k8s-output/DockerRegistryCredentials.yaml --kubeconfig k8s-output/api-server-kubeconfig

            - name: Create Docker registry credentials in Sync job
              command: kubectl apply -f k8s-output/DockerRegistryCredentials.yaml --kubeconfig k8s-output/sync-job-kubeconfig

#        - name: Deploy API
#          block:
#            - name: Deploy application
#              command: kubectl apply -f k8s-output/api --kubeconfig k8s-output/api-server-kubeconfig
#
#            - name: Wait for successful deployment
#              command: kubectl rollout status deployment dynamic-dns-api-deployment --kubeconfig k8s-output/api-server-kubeconfig -n {{ namespace }}

        - name: Deploy sync job
          block:
            - name: Create ConfigMap
              command: kubectl apply -f k8s-output/sync-job/ConfigMap.yaml --kubeconfig k8s-output/sync-job-kubeconfig

            - name: Deploy CronJob
              command: kubectl apply -f k8s-output/sync-job --kubeconfig k8s-output/sync-job-kubeconfig

    - name: Clean up output directory
      file:
        path: k8s-output
        state: absent
