---
- hosts: localhost
  connection: local

  tasks:
    - name: Build serverless fat JAR
      shell: cd ../ && sbt clean serverless/assembly

    - name: Deploy SAM application
      shell: |
        cd ../serverless && sam deploy