---
- hosts: localhost
  connection: local

  tasks:
    - name: Gather git information
      import_tasks: tasks/git-info.yml

    - name: Build serverless fat JAR
      shell: cd ../ && sbt clean serverless/assembly

    - name: Install npm dependencies
      command: npm --prefix serverless install

    - name: Initialize Serverless applcation
      shell: cd serverless && serverless create_domain

    - name: Deploy Serverless application
      shell: |
        cd serverless &&
          serverless deploy -v \
            --git_branch {{ git_branch }} \
            --git_commit {{ git_commit }} \
            --build_timestamp {{ ansible_date_time.iso8601 }}
