---
- hosts: localhost
  connection: local

  tasks:
    - name: Gather git information
      import_tasks: tasks/git-info.yml

    - name: Build serverless fat JAR
      shell: cd ../ && sbt clean serverless/assembly

    - name: Install npm dependencies
      command: npm --prefix serverless ci

    - name: Deploy Serverless application
      shell: |
        cd serverless &&
          SLS_DEBUG=* node_modules/.bin/serverless deploy \
            --param="git_branch={{ git_branch }}" \
            --param="git_commit={{ git_commit }}" \
            --param="build_timestamp={{ ansible_date_time.iso8601 }}"
